{
 "title": "RTSM",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Rate of Increase in Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method, endpoint, le) (\n  rate(hydra_http_request_duration_seconds_bucket{job=\"hydra-pods\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(hydra_container_cpu_usage_percent{job=\"hydra-pods\"})",
     "legendFormat": "Average CPU Usage %"
    }
   ]
  },
  {
   "title": "Hydra Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(hydra_container_memory_usage_mb{job=\"hydra-pods\"})",
     "legendFormat": "Average Memory Usage (MB)"
    }
   ]
  },
  {
   "title": "RL Decision Tracker",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "hydra_rl_last_action", "legendFormat": "RL Action" }
   ]
  },
  {
   "title": "Chaos Mesh Pipeline",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "hydra_rl_chaos_active", "legendFormat": "Infrastructure Status" }
   ]
  }
 ]
}