apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hydra

resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  - hydra-ns.yaml
  - pvc.yaml
  - rbac.yaml
  - hydra-depl.yaml
  - prometheus-depl.yaml
  - grafana-depl.yaml
  - frontend-depl.yaml
  - ingress.yaml
  - pdb.yaml
  - rl-controller.yaml

configMapGenerator:
- name: prometheus-config
  files:
    - prometheus/prometheus.yml

- name: grafana-prometheus-datasource
  files:
    - grafana/prometheus-ds.yml
